spring.application.name=college
server.port=8093
spring.datasource.url=jdbc:mysql://localhost:3306/sc
spring.datasource.username=root
spring.datasource.password=root
spring.jpa.hibernate.ddl-auto=update


